blank_issues_enabled: false
issue_template:
  - name: Bug Report
    about: Report a bug to help us improve.
    labels: ["bug", "triage"]
    file: bug_report.yml
  - name: Feature Request
    about: Suggest a new idea for the project.
    labels: ["enhancement"]
    file: feature_request.yml
